# Generated by Django 4.0.3 on 2022-05-23 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_text', models.TextField()),
                ('generated_text_1', models.TextField(default='')),
                ('generated_text_2', models.TextField(default='')),
                ('generated_text_3', models.TextField(default='')),
                ('prediction_time_sec', models.IntegerField(default=0)),
            ],
        ),
    ]
